spring.application.name=chapter1-backend

spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=chapter1
spring.datasource.password=1234
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.example.chapter1.domain
mybatis.configuration.map-underscore-to-camel-case=true

server.port=8080